app: helloapp
service: flask-api

provider:
  name: aws
  runtime: python3.8
  region: eu-central-1

functions:
  app:
    handler: wsgi_handler.handler
    timeout: 15
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'


custom:
  wsgi:
    app: estates.app
    pythonBin: python3
    packRequirements: false
  pythonRequirements:
    usePoetry: true
    dockerizePip: non-linux
  apigwBinary:
    types:
      - '*/*'

plugins:
  - serverless-wsgi
  - serverless-python-requirements
  - serverless-apigw-binary

package:
  patterns:
    - '!node_modules/**'
    - '!.venv/**'
    - '!notebooks/**'